apiVersion: v1 
kind: ConfigMap
metadata:
  name: payment
  labels:
    Project: roboshop
    component: payment
    tier: backend
  namespace: roboshop
data:
  CART_HOST: "cart"
  CART_PORT: "8080"
  USER_HOST: "user" 
  USER_PORT: "8080" 
  AMQP_HOST: "rabbitmq"
  AMQP_USER: "roboshop"
  AMQP_PASS: "roboshop123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  labels:
    Project: roboshop
    component: payment
    tier: backend
  namespace: roboshop
spec:
  replicas: 3
  strategy:
   type: RollingUpdate
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      Project: roboshop
      component: payment
      tier: backend
  template:
    metadata:
      labels:
        Project: roboshop
        component: payment
        tier: backend
    spec:
      containers:
      - name: payment
        image: akhilln/payment:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "100m"
        envFrom:
        - configMapRef:
            name: payment
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          failureThreshold: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          failureThreshold: 3
          periodSeconds: 10
---
apiVersion: v1 
kind: Service
metadata:
  name: payment 
  namespace: roboshop
spec:
  selector:
    Project: roboshop
    component: payment
    tier: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5