apiVersion: v1 
kind: ConfigMap
metadata:
  name: rabbitmq
data:
  RABBITMQ_DEFAULT_USER: "roboshop"
  RABBITMQ_DEFAULT_PASS: "roboshop123"
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    Project: roboshop
    component: rabbitmq
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: v1 
kind: Service
metadata:
  name: rabbitmq-headless
spec:
  clusterIP: None
  selector:
    Project: roboshop
    component: rabbitmq
    tier: db
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  selector:
    matchLabels:
      Project: roboshop
      component: rabbitmq
      tier: db
  serviceName: "rabbitmq-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        Project: roboshop
        component: rabbitmq
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
        - configMapRef:
            name: rabbitmq
        volumeMounts:
        - name: rabbitmq
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
