apiVersion: v1 
kind: Service
metadata:
  name: mysql
spec:
  selector:
    Project: roboshop
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1 
kind: Service
metadata:
  name: mysql-headless
spec:
  clusterIP: None
  selector:
    Project: roboshop
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      Project: roboshop
      component: mysql
      tier: db
  serviceName: "mysql-headless"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        Project: roboshop
        component: mysql
        tier: db
    spec:
      containers:
      - name: mysql
        image: akhilln/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql/
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
