apiVersion: v1 
kind: Service
metadata:
  name: redis
spec:
  selector:
    Project: roboshop
    component: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: v1 
kind: Service
metadata:
  name: redis-headless
spec:
  clusterIP: None
  selector:
    Project: roboshop
    component: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      Project: roboshop
      component: redis
      tier: db
  serviceName: "redis-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        Project: roboshop
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: akhilln/redis:v1
        volumeMounts:
        - name: redis
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "ebs-sc"
      resources:
        requests:
          storage: 1Gi
